# Generated by Django 2.2.2 on 2019-06-29 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attrition_report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrbp',
            name='test_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='hrbp',
            name='month',
            field=models.CharField(choices=[('January', 'JANUARY'), ('February', 'FEBRUARY'), ('March', 'MARCH'), ('April', 'APRIL'), ('May', 'MAY'), ('June', 'JUNE'), ('July', 'JULY'), ('August', 'AUGUST'), ('September', 'SEPTEMBER'), ('October', 'OCTOBER'), ('November', 'NOVEMBER'), ('December', 'DECEMBER')], default='JANUARY', help_text='Enter the Month to generate the report', max_length=20),
        ),
    ]
