# Generated by Django 2.2.2 on 2019-07-03 19:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attrition_report', '0003_remove_hrbp_test_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrbp',
            name='date_uploaded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='hrbp',
            name='excel_reference',
            field=models.FileField(help_text='Upload Excel Reference (Note: always clean data and do not change formatting)', upload_to='HRBP'),
        ),
    ]
