# Generated by Django 2.2.2 on 2019-07-03 20:15

import attrition_report.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attrition_report', '0004_auto_20190704_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrbp',
            name='excel_reference',
            field=models.FileField(help_text='Upload Excel Reference (Note: always clean data and do not change formatting)', storage=attrition_report.storage.OverwriteStorage(), upload_to='HRBP'),
        ),
    ]
