# Generated by Django 2.2.2 on 2019-07-04 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attrition_report', '0006_auto_20190704_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrbp',
            name='caf_pivot',
            field=models.FileField(blank=True, default='caf_pivot.png', null=True, upload_to='tmp'),
        ),
    ]
