# Generated by Django 2.2.2 on 2019-07-04 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attrition_report', '0009_auto_20190704_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrbp',
            name='by_dep_attrition',
            field=models.ImageField(blank=True, default='tmp/by_dep_attrition.png', null=True, upload_to='tmp/'),
        ),
        migrations.AddField(
            model_name='hrbp',
            name='count_pivot',
            field=models.ImageField(blank=True, default='tmp/count_pivot.png', null=True, upload_to='tmp/'),
        ),
        migrations.AddField(
            model_name='hrbp',
            name='g_a',
            field=models.ImageField(blank=True, default='tmp/G&A.png', null=True, upload_to='tmp/'),
        ),
        migrations.AddField(
            model_name='hrbp',
            name='gss',
            field=models.ImageField(blank=True, default='tmp/GSS.png', null=True, upload_to='tmp/'),
        ),
        migrations.AddField(
            model_name='hrbp',
            name='it',
            field=models.ImageField(blank=True, default='tmp/IT.png', null=True, upload_to='tmp/'),
        ),
        migrations.AddField(
            model_name='hrbp',
            name='marketing',
            field=models.ImageField(blank=True, default='tmp/Marketing.png', null=True, upload_to='tmp/'),
        ),
        migrations.AddField(
            model_name='hrbp',
            name='sales_ops',
            field=models.ImageField(blank=True, default='tmp/Sales Ops.png', null=True, upload_to='tmp/'),
        ),
    ]
